version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "generateJWT"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j893bzfi7hya"
s3_prefix = "generateJWT"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApiKey=\"\" SecretKey=\"\""

