AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  GenerateJWT

  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GenerateJWT:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: generate-jwt/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          API_KEY: !Ref ApiKey
          SECRET_KEY: !Ref SecretKey
      #Events:
      #  GetJWT:
      #    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #    Properties:
      #      Path: /jwt
      #      Method: get

Parameters:
  ApiKey:
    Type: String
  SecretKey:
    Type: String

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  #GenerateJWTdApi:
    #Description: "API Gateway endpoint URL for Prod stage for GenerateJWT function"
    #Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/jwt/"
  GenerateJWT:
    Description: "GenerateJWT Lambda Function ARN"
    Value: !GetAtt GenerateJWT.Arn
  GenerateJWTIamRole:
    Description: "Implicit IAM Role created for GenerateJWT function"
    Value: !GetAtt GenerateJWTRole.Arn
